version: '3.8'

services:
  app:
    build: .
    container_name: controlhub-app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: controlhub-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: controlhub
      MYSQL_USER: controlhub_user
      MYSQL_PASSWORD: secret
      TZ: Europe/Moscow
    ports:
       - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dbdata: 
